# Generated by Django 2.1.5 on 2021-09-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_auto_20210913_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='tipodocumento',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
