# Generated by Django 2.1.5 on 2021-09-13 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0005_cita_clasecita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiasclinica',
            old_name='socios',
            new_name='autorizacion',
        ),
        migrations.RemoveField(
            model_name='historiasclinica',
            name='prueba',
        ),
        migrations.RemoveField(
            model_name='historiasclinica',
            name='usuario',
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='comonosconocio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='contrato',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='cuotamod',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='eps',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='escolaridad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='fechaatencion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='horaatencion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelos.Cita'),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='pin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='profesion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
