# Generated by Django 2.1.5 on 2021-09-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0006_auto_20210913_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiasclinica',
            name='abd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='direccionAcompañante',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='enfermedadactual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='fc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='imc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='motivoconsulta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='nombreAcompañante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='parentescoAcompañante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='peso',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='responsableApellidosAcompañante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='responsableNombresAcompañante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='superficiecorporal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='ta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='talla',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='telefonoAcompañante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historiasclinica',
            name='temperatura',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
