# Generated by Django 2.1.5 on 2021-09-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0008_historiasclinica_ocupacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiasclinica',
            name='parentescoResponsable',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
