# Generated by Django 2.1.5 on 2021-09-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0010_auto_20210914_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=1000, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=1000, null=True)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=500, null=True)),
                ('telefono', models.CharField(blank=True, max_length=500, null=True)),
                ('tipodocumento', models.CharField(blank=True, max_length=1000, null=True)),
                ('numerodocumento', models.CharField(blank=True, max_length=500, null=True)),
                ('movil', models.CharField(blank=True, max_length=500, null=True)),
                ('correo', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cita',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='fechanacimiento',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='movil',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='numerodocumento',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='tipodocumento',
        ),
        migrations.AlterField(
            model_name='historiasclinica',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelos.Paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelos.Paciente'),
        ),
    ]
