# Generated by Django 2.1.5 on 2021-09-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0015_auto_20210923_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='codigo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
